# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oms/execution_reports.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oms/execution_reports.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oms import orders_pb2 as oms_dot_orders__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1boms/execution_reports.proto\x12\x03oms\x1a\x10oms/orders.proto\"\xd2\x03\n\x0f\x45xecutionReport\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x17\n\x0f\x63lient_order_id\x18\x03 \x01(\t\x12\x19\n\x11\x65xchange_order_id\x18\x04 \x01(\t\x12$\n\x06status\x18\x05 \x01(\x0e\x32\x14.oms.ExecutionStatus\x12\x1c\n\x04side\x18\x06 \x01(\x0e\x32\x0e.oms.OrderSide\x12\x17\n\x0flast_filled_qty\x18\x07 \x01(\x01\x12\x19\n\x11last_filled_price\x18\x08 \x01(\x01\x12\x1d\n\x15\x63umulative_filled_qty\x18\t \x01(\x01\x12\x11\n\tavg_price\x18\n \x01(\x01\x12\x12\n\ncommission\x18\x0b \x01(\x01\x12\x18\n\x10\x63ommission_asset\x18\x0c \x01(\t\x12\x15\n\rreject_reason\x18\r \x01(\t\x12\x15\n\revent_time_ns\x18\x0e \x01(\x03\x12\x14\n\x0crecv_time_ns\x18\x0f \x01(\x03\x12\x10\n\x08trace_id\x18\x10 \x01(\t\x12\x0f\n\x07\x66ill_id\x18\x11 \x01(\t\x12\x10\n\x08\x66ill_seq\x18\x12 \x01(\x05\x12\x16\n\x0eschema_version\x18\x13 \x01(\r*\x91\x01\n\x0f\x45xecutionStatus\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x07\n\x03NEW\x10\x01\x12\x14\n\x10PARTIALLY_FILLED\x10\x02\x12\n\n\x06\x46ILLED\x10\x03\x12\x0c\n\x08\x43\x41NCELED\x10\x04\x12\x0c\n\x08REJECTED\x10\x05\x12\x0b\n\x07\x45XPIRED\x10\x06\x12\x12\n\x0ePENDING_CANCEL\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oms.execution_reports_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXECUTIONSTATUS']._serialized_start=524
  _globals['_EXECUTIONSTATUS']._serialized_end=669
  _globals['_EXECUTIONREPORT']._serialized_start=55
  _globals['_EXECUTIONREPORT']._serialized_end=521
# @@protoc_insertion_point(module_scope)
